# Generated by Django 5.0.7 on 2024-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
