# Generated by Django 5.0.7 on 2024-07-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_factura", models.CharField(max_length=50, unique=True)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("correo", models.EmailField(max_length=254)),
                ("rfc", models.CharField(max_length=13)),
                ("otros_datos", models.TextField(blank=True)),
                ("pdf_path", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
